### ISSUE TITLE
Marble strings should ignore whitespace

### ISSUE THREAD

**Issue by stefnoten** [meltedspark/jest-marbles#81]
The readme seems to suggest to align marbles using spaces, *outside* of the marble string:
```
const e1 = hot('----a--^--b-------c--|', {a: 0});
const e2 = hot(  '---d-^--e---------f-----|', {a: 0});
```

However, this alignment whitespace is removed every time one reformats code in an IDE. For this reason, other marble testing libraries allow using whitespace *within* the marble string:
```
const e1 = hot('----a--^--b-------c--|', {a: 0});
const e2 = hot('  ---d-^--e---------f-----|', {a: 0});
```

This library interprets a space as a time frame, making this alignment strategy impossible.

**Comment by stefnoten** [comment]
Example reproduction:
```
const input = hot('   --a|');
const expected = hot('--a|');
expect(input).toBeObservable(expected);
```

Output:
```
Expected notifications to be:
  "--a|"
But got:
  "-----a|"
```

**Comment by meltedspark** [comment]
Good point, will implement.  
You are also welcome to create a PR yourself if you don't like to wait.
