### ISSUE TITLE
toBeObservable does not appear to support expect.objectContaining

### ISSUE THREAD

**Issue by spyderz42** [meltedspark/jest-marbles#90]
I am trying to convert my project from karma to jest, but I can not get toBeObservable to work with specifying partial objects. 

expect(this.effect$).toBeObservable(cold('-b', { b: expect.objectContaining({x:1, y:2} }));

Always returns false.

**Comment by meltedspark** [comment]
The same code works with `jasmine-marbles`?

**Comment by spyderz42** [comment]
Yes, albeit the expect.objectContaining is jest, not jasmine. So in jasmine we had jasmine.objectContaining<OurClass>({x:1,y:2})

**Comment by meltedspark** [comment]
Could you please provide a repository with a minimal reproduction, I'll take a look?

**Comment by spyderz42** [comment]
I can try, but I am not certain when I will be able to. This is internal customer code, and they will not let us release it, so I will have to recreate from scratch at home. 

I think the problem is in src/jest/custom-matchers.ts lines 26 and 27. Instead of trying to compare possible expect objects, it converts them to JSON strings and compares those strings.

**Comment by meltedspark** [comment]
@spyderz42 You're probably right, I'll take a look. It would be nice to have a real test case to cover though.

**Comment by spyderz42** [comment]
Took me a bit but this is pretty close to the test I have been trying to use at work:

diff --git a/spec/to-be-observable.spec.ts b/spec/to-be-observable.spec.ts
index 9454de7..d7c25af 100644
--- a/spec/to-be-observable.spec.ts
+++ b/spec/to-be-observable.spec.ts
@@ -62,4 +62,17 @@ describe('toBeObservable matcher test', () => {
     expect(hotInput).toBeObservable(expected);
     expect(coldInput).toBeObservable(expected);
   });
+
+  it('Should work for partial value objects', () => {
+    const valueObject = { foo: 'bar', x: 0, y: 0 };
+    const a$ = cold('-a-|', { a: valueObject });
+    // works
+    const expected = cold('-a-|', { a: {foo: 'bar', x: 0, y: 0} });
+    // doesn't work due to order of fields
+    const expected = cold('-a-|', { a: {x: 0, y: 0, foo: 'bar'} });
+    // doesn't work for partial object
+    const expected = cold('-a-|', { a: expect.objectContaining({x: 0, y: 0}) });
+
+    expect(a$).toBeObservable(expected);
+  });
 });

**Comment by meltedspark** [comment]
Cool, thanks! The fix is on its way.

**Comment by meltedspark** [comment]
Fixed in [v2.3.0](https://www.npmjs.com/package/jest-marbles/v/2.3.0).
